# Generated by Django 2.0.7 on 2018-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0002_auto_20180711_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
