# Generated by Django 2.0.7 on 2018-07-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0003_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
